### ISSUE TITLE
Consider making end_point_value (bezier and linear) be T instead of T-1

### ISSUE THREAD

**Issue by shawnisingh** [AOMediaCodec/iamf#354]
Currently, the "end_point_value" of segments (subblocks) of a parameter are defined to be located on the "last tick of the segment", i.e. T-1.

This means that the value of the parameter between T-1 and T is undefined.  This could be a problem if a slow parameter rate is used.

Advantages of this proposed approach:
- It allows for more natural way to express G0 continuity and to express an intentional discontinuity
- It better matches many common ways of representing piecewise curves with control points
- For an algorithm that computes parameter blocks from a given automation curve, this approach (optionally) allows an algorithm to determine segments and blocks without having to know the exact parameter rate
- The value of the parameter between T-1 and T is well defined with the new approach

**Comment by sunghee-hwang** [comment]
It seems to me that it makes a sense. 
In that case, should we change the below equation as well?

t1 = round(T * control_point_relative_time) - 1. to t1 = round(T * control_point_relative_time).

Please check it as well. 

Anyway it is better to use another word to distinguish "T" for this from "T" for the class. 
My suggestion is to use the word D instead of T.
