### ISSUE TITLE
Consider adding an anchored loudness field

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#359]

**Comment by shawnisingh** [comment]
For context, ATSC A85 defines an anchor element as "The perceptual loudness reference point or element around which other elements are balanced in producing the final mix of the content, or that a reasonable viewer would focus on when setting the volume control."

The prime example of an anchor element is dialog

The idea then is to normalize audio content such that the anchor element is adjusted towards the target reference loudness.

The advantage:
Anchor loudness can potentially be a natural way to normalize.  One content could be on average quieter simply because it has less dialogue and has more quiet moments.  Another content could be louder on average, for example if it had more action and drama that was often louder than dialogue.  Normalizing those two contents to the same target could feel odd.  Normalizing them based on dialog or anchor element is nice.

The disadvantage:
While there are tools to measure something like dialog loudness automatically, ultimately this anchor loudness approach puts faith in content providers to be aware of requirements and not abuse the system.  Broadcast systems have laws and quality control processes that help ensure it works well most of the time.  But I wonder if other places may have more challenges to deal with, in particular, content providers that may not be as aware of audio production requirements and may not be able to afford automated tools to solve it, or even the small portion of content that may be produced intentionally wrong.

My personal opinion:  I am in favor of adding anchor loudness, but perhaps we should have a complete discussion of whether this disadvantage is important or not, and if there's a way to solve it.  We'd also want to discuss whether it should be optional for a playback system to honor it, and related questions.

**Comment by sunghee-hwang** [comment]
I read that ATSC A/85 created in 2013. It would be good if we could make sure if it is open technology.

**Comment by sunghee-hwang** [comment]
If IAMF spec is going to support this, 
- Does it require to describe the generation method of the anchored loudness something like section 9.5.1?
(If it does, then which section of A/85 should be referred?)
- Does it require a different operation of devices compared to the current operation based on the value of `integrated_loudness`? (i.e. Does it require a new syntax for the anchored loudness?). Otherwise, Would it be okay just to set the value of `anchored_loundess` to `integrated_loudnes` field without introducing a new field for `anchored_loudness`?

For example, let's assume that `integrated_loudness` = -23 LKFS and `anchored_loudness` = -20 LKFS. 
If devices target -16 LKFS, then they do up 7 dB when they refer to `integrated_loudness`  or 4 db when they refer to `anchored_loudness`.

**Comment by sunghee-hwang** [comment]
It is closed as it has been resolved through PR #374.
