### ISSUE TITLE
§3.2, §3.6: Max size of obu_header and audio_element_obu

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#656]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§3.2, §3.6|

#### Comment:
```
if (obu_extension_flag == 1) {
      leb128() extension_header_size;
      unsigned int (8*extension_header_size) extension_header_bytes;
    }
```
would allow 4GB extension header bytes. Any concerns here? Should it be restricted to a certain limit? Should it use fixed size length signaling which allows reasonable amount of size signaling?

Same question regarding audio_element_obu for param_definition_bytes and audio_element_config_bytes. which probably will not require max range of 4GB.

-----
#### Suggestion:
Clarify the range of OBU header and similar elements.

**Comment by cconcolato** [comment]
There was a [review](https://github.com/AOMediaCodec/iamf/issues/512) made of the use of leb128, and one suggestion was to change some occurrences to fixed types, but it was not accepted. However, I agree we should have practical limits, maybe in profiles.

**Comment by sunghee-hwang** [comment]
The current spec mandates the extension_flag set to 0 for this version of the specification. Also, the current parsers would skip the extension_header_bytes of a known OBU with extension_flag = 1. When the current IAMF decoders buffer OBUs, the matter would be the obu_size rather than the extension_header_size.
So, I am not sure that limiting the size of the extension header is necessarily required for this version of the specification.

At this moment, I see no problem even though the future spec limits the size of the extension header.

Nevertheless, if we need to limit the size, how about one of 127 (7 bits) and 4095 (14 bits) bytes?

**Comment by felicialim** [comment]
Similarly with other extension bytes (audio element, rendering etc), the current spec already states that parsers should ignore these bytes. Or if we state that these extension sizes should be 0 in this version of the spec, would this be sufficient to address the concern?

**Comment by tdaede** [comment]
If we choose by profile, we can compute the max LPCM frame size for that profile, multiply by number of substreams, and make it ~10x larger than that as an approximation.

**Comment by sunghee-hwang** [comment]
- Sampling Rate: 192kHz
- Bit depth: 24 bits
- Number of Channels per Substream: 2
- Frame Duration: 40ms
==> 192000 x 3 bytes x 2 x 0.04 = 46,080 bytes

Here are several options for the maximum size of an OBU packet.
- 1M bytes (i.e., 2^20 bytes) ==> Maximum obu_size = 2^20 - 4 bytes
- 4M bytes ==> Maximum obu_size = 2^22 - 5 bytes
- 16M bytes  ==> Maximum obu_size = 2^24 - 5 bytes 
- 64M bytes ==>  Maximum obu_size = 2^26 - 5 bytes
- 256M bytes  ==> Maximum obu_size = 2^28 - 5 bytes
- 1024M bytes  ==> Maximum obu_size = 2^30 - 6 bytes
